default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: queue_multidb_development
  solid_queue:
    <<: *default
    database: queue_multidb_solid_queue_development
    migrations_paths: db/solid_queue_migrate

test:
  primary:
    <<: *default
    database: queue_multidb_test

production:
  primary:
    <<: *default
    database: queue_multidb_production
    username: queue_multidb
    password: <%= ENV["QUEUE_MULTIDB_DATABASE_PASSWORD"] %>
  solid_queue:
    <<: *default
    url: <%= ENV["SOLID_QUEUE_DATABASE_URL"] %>
    migrations_paths: db/solid_queue_migrate
